# Generated by Django 3.2.14 on 2024-09-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_vencimiento', models.DateField()),
                ('correo', models.CharField(max_length=300)),
            ],
        ),
    ]
