# Generated by Django 3.2.14 on 2024-09-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tareas',
        ),
    ]
