# Generated by Django 3.2.14 on 2024-09-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Estado',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('pendiente', 'pendiente'), ('vencida', 'vencida'), ('terminada/vencida', 'terminada/vencida')], max_length=20),
        ),
    ]
